// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJHwg7b5cgZS3TJuyJ3la1C3dGuxGY4k',
    appId: '1:206847009258:web:0722cf7d905855db40d293',
    messagingSenderId: '206847009258',
    projectId: 'chat-app-2edef',
    authDomain: 'chat-app-2edef.firebaseapp.com',
    storageBucket: 'chat-app-2edef.firebasestorage.app',
    measurementId: 'G-GQC3DG7SGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9G5QaUT40q8Hlyw83uB9TN-Zm6gyxveo',
    appId: '1:206847009258:android:ee028e356d73a89840d293',
    messagingSenderId: '206847009258',
    projectId: 'chat-app-2edef',
    storageBucket: 'chat-app-2edef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPP7W3AGrvH5wwlHNl8GUoeeLkB7e64Pw',
    appId: '1:206847009258:ios:d0fa814af58b9c9240d293',
    messagingSenderId: '206847009258',
    projectId: 'chat-app-2edef',
    storageBucket: 'chat-app-2edef.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPP7W3AGrvH5wwlHNl8GUoeeLkB7e64Pw',
    appId: '1:206847009258:ios:d0fa814af58b9c9240d293',
    messagingSenderId: '206847009258',
    projectId: 'chat-app-2edef',
    storageBucket: 'chat-app-2edef.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyJHwg7b5cgZS3TJuyJ3la1C3dGuxGY4k',
    appId: '1:206847009258:web:8f685e1fd6af4f4640d293',
    messagingSenderId: '206847009258',
    projectId: 'chat-app-2edef',
    authDomain: 'chat-app-2edef.firebaseapp.com',
    storageBucket: 'chat-app-2edef.firebasestorage.app',
    measurementId: 'G-7CNZF5DKE3',
  );

}